---
title: "Preparing before Plotting"
author: "Kathy Condon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# call commonly used libraries
library(knitr)
library(tidyverse)
library(dplyr)
library(car)
library(emmeans)
library(multcomp)
library(lmerTest)
library(lme4)
library(RColorBrewer)
library(rstatix)
library(tidyr)
library(ggpubr)
library(lubridate)
library(ggtext)
library(ggh4x)
library(ggpattern)
library(data.table)
library(MuMIn)
library(scales)
library(performance)

# create plot theme (formatting changes)
plot_theme<-theme_classic()+
  theme(
    
    # facet strips
    strip.background=element_blank(),
    strip.text.x=element_text(size=12,
                              hjust=0,
                              face="bold",colour="black"),
    strip.text.y=element_text(size=12,
                              hjust=0,
                              face="bold",colour="black"),
    strip.placement="outside",
    
    # panel and plot
    panel.background=element_rect(fill="transparent"),
    panel.border=element_rect(fill="transparent",color="black",
                              linewidth=0.5),
    plot.background=element_rect(fill="transparent",color=NA),
    plot.title=element_text(size=12),
    
    # legend changes
    legend.background=element_rect(fill="transparent"),
    legend.position="none",
    # legend.title=element_text(size=16,face="bold"),
    legend.text=element_text(size=12),
    
    # axes changes
    # axis.line.x=element_line(linewidth=1,color="black"),
    axis.line.x=element_blank(),
    axis.line.y=element_blank(),
    axis.ticks=element_line(linewidth=0.5,color="black"),
    axis.ticks.length=unit(-0.05,"in"),
    axis.title = element_text(size=12,
                              colour="black",face="bold"),
    axis.text=element_text(size=10,colour="black"),
    axis.text.x=element_text(angle=0,hjust=0.5,colour="black"),
    axis.text.y=element_text(colour="black"))
  
```

```{r data}
# read in data


# change data types as needed



```


```{r plotting}




```



